name: top-repo-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - altair_saver=0.5.0
  - geopy=2.2.0
  - matplotlib=3.5.1
  - numpy=1.21.5
  - pandas=1.3.5
  - pygithub=1.55
  - tqdm=4.62.3
  - vega_datasets=0.9.0
  - wordcloud=1.8.1
  - pip>=21
  - pip:
    - docopt==0.6.2
